### ISSUE TITLE
Weird occlusion culling problem

### ISSUE THREAD

**Issue by kring** [CesiumGS/cesium-unreal#1288]
Originally reported on the community forum:
https://community.cesium.com/t/tiles-constantly-glitching-in-certain-zones/27648

In this one particular spot, near latitude 49.9889 longitude -113.410537, there's a very strange flickery visual glitch in Cesium World Terrain when you move the camera in close to the surface. The problem goes away when the Cesium3DTileset Actor is selected. It also goes away when you turn off Unreal's Occlusion Culling (Edit->Project Settings->Engine->Rendering->Culling). 

I believe what is happening is that Unreal is changing its mind every other frame about whether or not these tiles are occluded. So one frame they're rendered, the next they're not, and so on. If you do `r.VisualizeOccludedPrimitives 1` in the console, Unreal highlights these flickery tiles in green, indicating that they are occluded (at least some of the time):

<img width="694" alt="image" src="https://github.com/CesiumGS/cesium-unreal/assets/924374/572cf1c9-f48c-49a9-acac-e30d3a891edb">

This is with "Suspend Update" enabled, so I don't think there's any possibility that we're accidentally toggling the tile's visibility on and off.

I have no idea what's causing this occlusion ping-pong, though. Seems like it kind of has to be an Unreal Engine bug, but hard to say for sure. I tested with UE 5.1.1.

![occlusion-culling-artifact](https://github.com/CesiumGS/cesium-unreal/assets/924374/eb9551ca-ec96-42f0-b29d-2696e7a155ed)

**Comment by j9liu** [comment]
I can't actually seem to reproduce this on 5.2, 5.3 or 5.4. I made sure that Occlusion Culling was turned on, and I zoomed around the area for a while, but could never see that flickering.

If someone else wants to gut check for me whether or not they can see it, definitely feel free. But it may have just been resolved with newer versions of Unreal.

**Comment by j9liu** [comment]
I wonder if this is the same / similar problem to https://github.com/CesiumGS/cesium-unreal/issues/914?

Though, people on that thread have reported having the problem in 5.2 and 5.3. I downloaded one of the users' datasets  but I still can't reproduce the problems myself. 🤔

**Comment by kring** [comment]
It's probably worth seeing if we can still reproduce this in 5.1, because if we can, and then we can't in 5.2, that would drastically increase my confidence that it was fixed in 5.2. I still have 5.1 installed, so I'll try it before I uninstall it.

**Comment by kring** [comment]
I can still reproduce this in UE 5.1.1. It took me a little bit of flying around to get it to happen, though. I'll try 5.2 next.

**Comment by kring** [comment]
It still happens in UE 5.4.1, too.
![image](https://github.com/CesiumGS/cesium-unreal/assets/924374/7dd8b40b-5baa-4603-9b16-3f713b28f478)

**Comment by j9liu** [comment]
Hm I still can't reproduce this error on my machine, regardless of engine version. And I tried this too on our office desktop, on 5.1 No dice.

I'm going to the specified long / lat and am flying around, trying to find flickering tiles. Is this what you're doing, too? Is there a particular place that is more problematic than others?

Maybe this is a hardware issue? I know you have an AMD GPU, but both my laptop + our office desktop use NVidia GPUs.

**Comment by kring** [comment]
> Maybe this is a hardware issue? I know you have an AMD GPU, but both my laptop + our office desktop use NVidia GPUs.

I have an Intel Arc A750. I'll see if I can reproduce it on my laptop with a NVidia GTX 1650.

**Comment by kring** [comment]
It's not as obvious on the GTX 1650, but there's still some flickering weirdness going on at that location. Even without moving the camera, tiles near the edges and occassionally right in the middle flicker on and off. Just like on my other system, turning off Occlusion Culling or selecting the Cesium3DTileset in the outliner makes the problem go away.

https://github.com/CesiumGS/cesium-unreal/assets/924374/89a36bc8-4416-462f-9e1d-f2bea626132b

**Comment by EvenZHAnglll** [comment]
In our case, we also encountered this occlusion culling flickering issue. After our investigation, we found several workarounds:

- Setting the GeoReference origin coordinates to (0,0,0) prevents the flickering. However, this means that the ground-level scene will be very far from UE's world origin.

- Using the latest version of the Cesium for Unreal plugin and using the procedural earth (the "From Ellipsoid" option in 3DTiles) also resolves the issue, but this only works for flat TMS map.

- Enabling the custom depth option for 3DTiles can stop the flickering, but it may interfere with other visual effects that rely on custom depth buffer.

I hope to find a proper solution to this issue.

**Comment by kring** [comment]
The least invasive workaround that I'm aware of @EvenZHAnglll is mentioned in the top post: disable Unreal's occlusion culling feature.

**Comment by EvenZHAnglll** [comment]
> The least invasive workaround that I'm aware of [@EvenZHAnglll](https://github.com/EvenZHAnglll) is mentioned in the top post: disable Unreal's occlusion culling feature.


This is a valid solution! 
I initially didn’t try this option because I thought it would have a significant performance impact. Since our scene contains a lot of Unreal's assets static mesh.

However, after testing it in practice, I found that it doesn’t cause any noticeable performance issues, as the occlusion culling setting does not affect nanite mesh occlusion culling at all. Nanite meshes are still culled at the cluster level.
